### ISSUE TITLE
Cannot find model_final.pt 

### ISSUE THREAD

**Issue by Nelhachem** [idekerlab/nest_vnn#1]
Hi,

I recently had the pleasure of reading your insightful paper titled "A deep learning model of tumor cell architecture elucidates response and resistance to CDK4/6 inhibitors." Your approach to predicting drug response is both novel and promising, and I am in process to apply it to my own research.

Currently, I am working on predicting drug associations for a specific compound using the Genomics of Drug Sensitivity in Cancer (GDSC) dataset. However, I encountered a small obstacle – I was unable to locate the 'model_final.pt' file for testing purposes.

I kindly request your guidance on this matter

Thanks

**Comment by aksinghal5590** [comment]
Hi, 'model_final.pt' is the model's name if you train a new model. For testing purposes, we have several pre-trained models in the "pretrained_models" folder. You can try any of those.

I've also added a test script "sample/test_palbociclib.sh" which runs the pre-trained palbociclib model "sample/pretrained_model_outputs/palbociclib_1/model_Palbociclib_1.pt" and outputs the results in the same folder.

Hope it helps!

**Comment by Nelhachem** [comment]
Thank you! I'll give a try
