### ISSUE TITLE
Why I got the same value in predict file?

### ISSUE THREAD

**Issue by Jacob-0221** [idekerlab/nest_vnn#3]
#2 
Hi Akshat,

Thanks for your help! Sorry for the delay. I have run the "test_palbociclib.sh" and got the right results. However, I'm trying to use the train.sh file to train the model, and I did not change the code. Then I use the test.sh to get the predict file based on the trained model. However, I still got the same value in the predict.txt. I don't know why I got the same value. All the input files and codes were same as the guidance. 

Since you have closed the issue #2, I create a new issue. 

I'm looking forward to your guidance and suggestions.

Thanks,

Jacob

**Comment by aksinghal5590** [comment]
Hi Jacob, train.sh is an example file to check if one can train a model. To train a correct model you will need the drug response data for the drug of your choice. The cell line data in this repo is for palbociclib. After you have collected all the cell line and drug response data, you will have to optimize the hyperparameters. For example, "epoch" in the current file is set to 2. Its correct value should be more than 100.

**Comment by Jacob-0221** [comment]
Hi Akshat,

Thanks for your help! I know why I get the wrong results after your explanation. I'll try later.

Best wishes,

Jacob
